### ISSUE TITLE
 Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by mondersky** [mathieuf20/FormAssistant-SaveAndRestore#7]
I get this issue on my console
```
Error handling response: TypeError: Cannot read properties of undefined (reading 'replace')
    at F (chrome-extension://eoccmgkpiljbelbbhkjpagljajmikjme/javascripts/mousetrap.min.js:5:378)
    at Object.bind (chrome-extension://eoccmgkpiljbelbbhkjpagljajmikjme/javascripts/mousetrap.min.js:7:488)
    at chrome-extension://eoccmgkpiljbelbbhkjpagljajmikjme/javascripts/content_script.js:85:19
```

**Comment by mathieuf20** [comment]
Fixed in commit 5619516 on master.
